name : "Action to be done for greeting"
# on: push
on:
  schedule:
    - cron:  '30 1 * * *'

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mallikarjun"
